services:
    nginx:
        image: nginx:latest
        container_name: nginx-docker-app-nginx
        volumes:
            - ./frontend:/var/www/front/
            - ./backend/public:/var/www/html/public:rw
            - ./backend/storage/app/public:/var/www/html/storage/app/public
            - ./frontend/public/images:/var/www/html/public/storage/front:rW
            - ./.ci/nginx-default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "${APP_PORT:-80}:80"
        networks:
            - sail
        depends_on:
            - laravel.test
            - mysql
            - react
    laravel.test:
        build:
            context: ./
            dockerfile: ./.ci/php/local.dockerfile
            args:
                WWWGROUP: '${WWWGROUP:-20}'
        image: nginx-docker-app-laravel
        container_name: nginx-docker-app-laravel
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - './.env:/var/www/html/.env:ro'
            - './backend:/var/www/html'
            - './.ci/php.ini:/usr/local/etc/php/conf.d/php.ini'
        networks:
            - sail
        depends_on:
            - mysql
    mysql:
        image: 'mysql:8.0'
        container_name: mysql
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD:-secret}'
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD:-secret}'
        volumes:
            - 'sail-mysql:/var/lib/mysql'
            - './backend/vendor/laravel/sail/database/mysql/create-testing-database.sql:/docker-entrypoint-initdb.d/10-create-testing-database.sql'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-h'
                - 'localhost'
            retries: 3
            timeout: 5s
    react:
        build:
            context: ./
            dockerfile: ./.ci/react/local.dockerfile
        image: nginx-docker-app-front
        container_name: nginx-docker-app-front
        ports:
            - '3000:3000'
        volumes:
            - './frontend:/var/www/front/'
            - './.env:/var/www/front/.env:ro'
        networks:
            - sail
networks:
    sail:
        name: nginx-docker-app-network
        driver: bridge
        external: true
volumes:
    sail-mysql:
        driver: local
    sail-react:
        driver: local

